version: "2.3"
services:
  nginx:
    build: ./nginx #Указываем откуда будет вестись сборка
    ports: # Указываем какие порты нужно пробросить наружу
      - "80:80"
    volumes: #Подключаем рабочий каталог с кодом проекта
      - ./www:/var/www