version: "2.3" #Задаем версию docker-compose.yml
services: #Задаем контейнеры
  nginx: #Задаем название первого контейнера - nginx и настраиваем его
    build: ./nginx #Указываем откуда будет вестись сборка
    ports: # Указываем какие порты нужно пробросить наружу
      - "80:80"
    volumes: #Подключаем рабочий каталог с кодом проекта
      - ./www:/var/www